messages:
  no-perm: "&6Префиксы &8| &fУ вас недостаточно прав."
  prefix-size: "&6Префиксы &8| &fПрефикс слишком большой."
  successful-change: "&6Префиксы &8| &fВаш префикс изменён на &r{prefix}"
  prefix-on: "&6Префиксы &8| &fВаш префикс успешно включён."
  prefix-off: "&6Префиксы &8| &fВаш префикс успешно выключен."
  prefix-reset: "&6Префиксы &8| &fВаш префикс успешно сброшен."
  prefix-save: |-
    &6Префиксы &8| &fПрефикс &r{prefix} &6#{n} &fуспешно сохранён!
    &6Префиксы &8| &fЧтобы загрузить его, используйте команду &e/prefix load {n}
  prefix-list:
    header: "&6Префиксы &8| &fВаши сохраненные префиксы:"
    foreach: "  &7#{n} - {prefix}"
    hover: "&6Нажми&7, чтобы загрузить префикс &6#{n}"
  prefix-not-found: |-
     &6Префиксы &8| &fДанный префикс не сохранен.
     &6Префиксы &8| &fСписок сохраненных префиксов - &e/prefix list
  prefix-deleted: "&6Префиксы &8| &fПрефикс успешно удалён."
  prefix-limit: |-
    &6Префиксы &8| &fВы использовали все свободное место для хранения префиксов!
    &6Префиксы &8| &fЧтобы удалить сохраненный префикс, используйте - &e/prefix remove номер
  prefix-load: "&6Префиксы &8| &fПрефикс &r{prefix} &6#{n} &7успешно загружен!"
  prefix-info: |-
    &6Префиксы &8| &fИнформация:
    &6* &fВаш текущий префикс - {prefix}
    &6* &fСохранено префиксов - {n}/{max}
  prefix-help: |-
   &6Префиксы &8| &fСписок команд:
   &6* &fУстановить префикс - &e/prefix set
   &6* &fСбросить префикс - &e/prefix reset
   &6* &fCохранить префикс - &e/prefix save
   &6* &fЗагрузить префикс - &e/prefix load
   &6* &fСписок сохранённых префиксов - &e/prefix list
   &6* &fУдалить сохраненный префикс - &e/prefix del
  prefix-format: "&6Префиксы &8| &fВы не можете использовать данные чат-коды в префиксах."

prefix:
  'off':
    chat: "&7"
    tab: "&7"

prefix-limit:
  vip: 5
  owner: -1
